#!/bin/bash


#Color scheme
######
# Reset
Color_Off='\e[0m'       # Text Reset

# Regular Colors
Yellow='\e[0;33m'       # Yellow
Red='\e[0;31m'          # Red
Green='\e[0;32m'        # Green
#######
# -i {path}	include. Sets env var of includes folder
# -s {char}	spaces. Change spaces for the character specified (useful to check presentation)
# -n {string}	new. Creates new ProTester project
# -c		compile. Compiles the program without running tests
usage="\n
LiTester 0.01a -- LI prolog projects -- Written by Dreth\n
 -s {char}	spaces. Change spaces for the character specified (useful to check presentation)\n
 -n {string}	new. Creates new LiTester project\n
 -c		compile. Compiles the program without running tests\n
 -e 		execute. Executes the program reading from stdin"
noOpts="42"
compileOnly=false
execute=false
recursiveMode=false
debugMode=false
spaceChar=' '
targetName=${PWD##*/}
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

#function setIncludes {
# 
#  echo export PATH=$1:$PATH
#}

#deprecated
function clearDir {
  if [ -f bin/$targetName.exe ]; then
    rm bin/$targetName.exe
  fi

}

function compile {
  echo "===Running tests for: "$targetName"==="
  echo "Compiling..."  
  echo "--"$targetName
  swipl -O -q -g main --stand_alone=true -o bin/$targetName.exe -c "src/$targetName.pl"

  if [ ! -f "bin/$targetName.exe" ]; then
    echo -e "${Yellow}### COMPILATION FAILED FOR: $targetName ###"
  echo -ne "${Color_Off}"
    exit
  fi

  echo -e "${Yellow}"
  
  if [ ! -f bin/$targetName.exe ]; then
    echo -e "### LINK FAILED ###"
    echo -ne "${Color_Off}"
    exit
  fi
  
  echo -ne "${Color_Off}"
}

function launch {
  if [ -f bin/$targetName.exe ]; then
    echo "Executing... NOW!"
    bin/$targetName.exe
  else
    echo "Nothing to launch"
  fi
}

function runTests {
  declare -i total
  total=0
  declare -i ok
  ok=0

  if [ -f bin/$targetName.exe ]; then

    for D in ./test/*; do
      if [ -d "${D}" ]; then
          cd "${D}"
          protester -t
          cd ../..
      fi
    done
    for f in test/*.in; do
      testFileName=${f%.*}
      testFileName=${testFileName##*/}
      bin/$targetName.exe < "test/$testFileName.in" > output/$testFileName.out
      cat "output/$testFileName.out" | sed -r "s/[ \t\n]/$spaceChar/g" > outputP.temp
      cat "test/$testFileName.out" | sed -r "s/[ \t\n]/$spaceChar/g" > outputW.temp
      total=total+1
      result=$(diff -y outputW.temp outputP.temp)
      if [ $? -eq 0 ]
      then
         ok=ok+1
         echo "$testFileName - OK"
      else
         echo -e "${Red}$testFileName - FAILED:"
         echo "$result"
         echo -e "${Color_Off}"
      fi
      rm outputP.temp outputW.temp
    done
  
    if [ $total -eq $ok ]; then
         echo -e "${Green}";
    else
         echo -e "${Red}";
    fi
    echo "PASSED: $ok/$total"
    echo -en "${Color_Off}"
  fi
}


function newProject {
  cp -r $DIR/litesterFiles $1
  mv $1/src/template.pl $1/src/$1.pl
  mkdir $1/output $1/bin
}

#Priority
while getopts  ":i:s:n:chetd" flag;
do
  case $flag in
    h)
      echo -e $usage
      exit 0
      ;;
    n)
      newProject ${OPTARG}
      exit 0
      ;;
  esac
done

OPTIND=1 #reset

while getopts  ":i:s:n:chetd" flag;
do
  case $flag in
    i)
      setIncludes ${OPTARG}
      ;;
    s)
      spaceChar=${OPTARG}
      ;;
    c)
      compileOnly=true
      ;;
    e)
      execute=true
      ;;
    t)
      recursiveMode=true
      ;;
    d)
      debugMode=true
      ;;
    *)
      echo $noOpts
      exit 0
      ;;
  esac
done

#clearDir 
compile 
if [ "$compileOnly" = false ]; then
  runTests 
fi
if [ "$execute" = true ]; then
  launch
fi

echo -ne "${Color_Off}"
